project_name: status
release:
  github:
    owner: bergerx
    name: kubectl-status
before:
  hooks:
    - go generate ./...
builds:
  - id: status
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/bergerx/kubectl-status/cmd/plugin/cli.version={{ trimprefix .Summary "v" }}
archives:
  - id: status
    builds:
      - status
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
