project_name: status
version: 2
release:
  github:
    owner: bergerx
    name: kubectl-status
before:
  hooks:
    - go generate ./...
    - go mod tidy
builds:
  - id: status
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/main.go
    ldflags: -s -w
      -X main.version={{ .Summary }}
archives:
  - id: status
    builds:
      - status
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
