apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: status
spec:
  version: {{ .TagName }}
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/bergerx/kubectl-status/releases/download/{{ .TagName }}/status_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "./status"
      to: "."
    - from: LICENSE
      to: "."
    bin: "status"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/bergerx/kubectl-status/releases/download/{{ .TagName }}/status_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "./status"
      to: "."
    - from: LICENSE
      to: "."
    bin: "status"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/bergerx/kubectl-status/releases/download/{{ .TagName }}/status_windows_amd64.zip" .TagName }}
    files:
    - from: "/status.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "status.exe"
  shortDescription: Show status details of a given resource.
  homepage: https://github.com/bergerx/kubectl-status
  caveats: |
    Usage:
      $ kubectl status

    For additional options:
      $ kubectl status --help
      or https://github.com/bergerx/kubectl-status/blob/master/doc/USAGE.md

  description: |
    Show status details of a given resource. Most useful when debugging Pod issues.
