# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: meta
    hooks:
    -   id: check-useless-excludes

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^.krew.yaml$
    -   id: check-added-large-files

-   repo: local
    hooks:

    # Usual pre-commit install only installs the pre-commit hook, trying to get
    # them installed through this hook.
    -   id: install-pre-push-hook
        name: install-pre-push-hook
        entry: pre-commit install -t pre-push
        language: system
        always_run: true
        pass_filenames: false

    -   id: make-test
        name: make test
        entry: make test
        language: system
        always_run: true
        pass_filenames: false

    -   id: make-test-e2e
        name: make test-e2e
        stages: [push]
        entry: make test-e2e
        language: system
        always_run: true
        pass_filenames: false
